# Generated by Django 6.0.3 on 2026-04-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptrequest',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='momo_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='momo_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='transcript_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
