# Generated by Django 6.0.3 on 2026-07-04 14:39

from django.db import migrations


def seed_prices(apps, schema_editor):
    ServicePrice = apps.get_model("core", "ServicePrice")
    prices = [
        # Transcripts
        {"category": "transcript", "label": "Undergraduate (Same day) within 24hrs", "price": 69, "order": 1},
        {"category": "transcript", "label": "Undergraduate (2 days) / 48hrs", "price": 46, "order": 2},
        {"category": "transcript", "label": "Undergraduate (One week)", "price": 23, "order": 3},
        {"category": "transcript", "label": "Additional Copy", "price": 12, "order": 4},
        {"category": "transcript", "label": "Postgraduate (Same day) within 24hrs", "price": 104, "order": 5},
        {"category": "transcript", "label": "Postgraduate (2 days) / 48hrs", "price": 69, "order": 6},
        {"category": "transcript", "label": "Postgraduate (One week)", "price": 35, "order": 7},
        {"category": "transcript", "label": "Additional Copy (Postgraduate)", "price": 18, "order": 8},
        {"category": "transcript", "label": "Transcript (Overseas)", "price": 231, "order": 9},
        {"category": "transcript", "label": "Transcript Overseas (Self Postage)", "price": 190, "order": 10},
        {"category": "transcript", "label": "Transcript Overseas (Email)", "price": 120, "order": 11},
        {"category": "transcript", "label": "Certification (5 Copies)", "price": 23, "order": 12},
        # Letters
        {"category": "letter", "label": "Proficiency in English", "price": 18, "order": 1},
        {"category": "letter", "label": "Attestation letter", "price": 18, "order": 2},
        {"category": "letter", "label": "Confirmation letter", "price": 18, "order": 3},
        {"category": "letter", "label": "Introductory letter (Visa)", "price": 35, "order": 4},
        {"category": "letter", "label": "Introductory letter (other purposes)", "price": 18, "order": 5},
    ]
    for p in prices:
        ServicePrice.objects.get_or_create(category=p["category"], label=p["label"], defaults=p)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_passwordresetcode"),
    ]

    operations = [
        migrations.RunPython(seed_prices),
    ]
