# Generated by Django 6.0.3 on 2026-07-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_service_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Payment', max_length=20),
        ),
    ]
