# Generated by Django 6.0.3 on 2026-07-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transcriptrequest_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
    ]
