# Generated by Django 6.0.3 on 2026-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='admin_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='student_read',
            field=models.BooleanField(default=False),
        ),
    ]
