# Generated by Django 6.0.3 on 2026-07-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_supportticket_admin_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptrequest',
            name='momo_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
