# Generated by Django 6.0.3 on 2026-07-15 23:12

from django.db import migrations, models


def map_legacy_pending_to_pending_review(apps, schema_editor):
    TranscriptRequest = apps.get_model('core', 'TranscriptRequest')
    TranscriptRequest.objects.filter(status='Pending').update(status='Pending Review')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transcriptrequest_momo_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Pending Review', 'Pending Review'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending Payment', max_length=20),
        ),
        migrations.RunPython(map_legacy_pending_to_pending_review, migrations.RunPython.noop),
    ]
